services:
  - type: web
    name: nexus-miner
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://nexus-miner.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: DB_PATH
        value: ./data/nexusminer.db
      - key: VAPID_PUBLIC_KEY
        value: BM82vq0c6Eef9gzlCY2MXShyaSliXjz2WxEGf8A_QVeZtVrAe0sint1usY6fAvEEf1kVDm4ZZ5aGij4dtXTfEoU
      - key: VAPID_PRIVATE_KEY
        value: dcIhtVvN7b5zQo5nQYSsrnwr6m0dAQmAm0MUbkx3jaU
      - key: VAPID_EMAIL
        value: mailto:admin@nexusminer.com
    autoDeploy: true
